import React, { useMemo, useState } from "react";
import PageHeader from "@/components/PageHeader";

function formatRupiah(value) {
  return new Intl.NumberFormat("id-ID", {
      style: "currency",
          currency: "IDR",
              maximumFractionDigits: 0,
                }).format(Number(value) || 0);
                }

                export default function Payrolls() {
                  const [payroll, setPayroll] = useState({
                      gajiPokok: 0,
                          tunjanganBbm: 0,
                              tunjanganKedisiplinan: 0,
                                  tunjanganGotongRoyong: 0,
                                    });

                                      const fields = [
                                          {
                                                key: "gajiPokok",
                                                      label: "Gaji Pokok",
                                                          },
                                                              {
                                                                    key: "tunjanganBbm",
                                                                          label: "Tunjangan BBM",
                                                                              },
                                                                                  {
                                                                                        key: "tunjanganKedisiplinan",
                                                                                              label: "Tunjangan Kedisiplinan",
                                                                                                  },
                                                                                                      {
                                                                                                            key: "tunjanganGotongRoyong",
                                                                                                                  label: "Tunjangan Gotong Royong",
                                                                                                                      },
                                                                                                                        ];

                                                                                                                          const totalGaji = useMemo(() => {
                                                                                                                              return (
                                                                                                                                    Number(payroll.gajiPokok || 0) +
                                                                                                                                          Number(payroll.tunjanganBbm || 0) +
                                                                                                                                                Number(payroll.tunjanganKedisiplinan || 0) +
                                                                                                                                                      Number(payroll.tunjanganGotongRoyong || 0)
                                                                                                                                                          );
                                                                                                                                                            }, [payroll]);

                                                                                                                                                              const handleChange = (field, value) => {
                                                                                                                                                                  setPayroll((prev) => ({
                                                                                                                                                                        ...prev,
                                                                                                                                                                              [field]: value,
                                                                                                                                                                                  }));
                                                                                                                                                                                    };

                                                                                                                                                                                      return (
                                                                                                                                                                                          <div className="p-6 lg:p-8 max-w-5xl mx-auto">
                                                                                                                                                                                                <PageHeader
                                                                                                                                                                                                        title="Payroll"
                                                                                                                                                                                                                subtitle="Kelola komponen gaji dan tunjangan karyawan"
                                                                                                                                                                                                                      />

                                                                                                                                                                                                                            <div className="grid md:grid-cols-2 gap-6">
                                                                                                                                                                                                                                    {/* FORM KOMPONEN GAJI */}
                                                                                                                                                                                                                                            <div className="bg-white rounded-2xl border border-slate-200/70 p-6">
                                                                                                                                                                                                                                                      <h3 className="font-semibold text-slate-900 mb-5">
                                                                                                                                                                                                                                                                  Komponen Gaji
                                                                                                                                                                                                                                                                            </h3>

                                                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                                                  {fields.map((item) => (
                                                                                                                                                                                                                                                                                                                <div key={item.key}>
                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium text-slate-600 mb-1.5">
                                                                                                                                                                                                                                                                                                                                                  {item.label}
                                                                                                                                                                                                                                                                                                                                                                  </label>

                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center border border-slate-200 rounded-xl overflow-hidden focus-within:border-indigo-400 focus-within:ring-2 focus-within:ring-indigo-500/10">
                                                                                                                                                                                                                                                                                                                                                                                                    <span className="px-4 text-sm text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                        Rp
                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    min="0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={payroll[item.key]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  handleChange(item.key, e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full py-3 pr-4 outline-none text-slate-900 tabular-nums"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* SUMMARY */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-gradient-to-br from-indigo-500 to-violet-600 rounded-2xl p-6 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-indigo-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Total Gaji
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-3xl font-bold mt-2 tabular-nums">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {formatRupiah(totalGaji)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-indigo-200 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Gaji pokok + seluruh tunjangan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-2xl border border-slate-200/70 p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-semibold text-slate-900 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Rincian Payroll
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {fields.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              key={item.key}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex items-center justify-between gap-4 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-slate-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="font-medium text-slate-900 tabular-nums text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {formatRupiah(payroll[item.key])}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="border-t border-slate-100 pt-4 mt-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="font-semibold text-slate-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Total
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="font-bold text-indigo-600 tabular-nums">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {formatRupiah(totalGaji)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }